# Config for the setup workflow and common resources (jobs, commands) for main workflows
# `common-` prefix is added for common resources (to avoid conflicts with module resources)
# Adding in a comment to trigger a pull request

version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.2.0

workflows:
  # The setup workflow
  setup:
    jobs:
      - continuation/continue:
          configuration_path: ".circleci/continue_config.yml"
          parameters: /tmp/circleci/config-string.json
          pre-steps:
            - checkout
            - run:
                name: Determine if we need to persist and export components
                command: |
                  PR_NUM=$(git show -s --format=%s $CIRCLE_SHA1|awk '{print $4}'|cut -c 2-)
                  echo $PR_NUM
                  if $PR_NUM -ne 0; then
                    echo '{ "EXEC_WF1": true }' >> /tmp/circleci/config-string.json
                  else
                    echo '{ "EXEC_WF2": true }' >> /tmp/circleci/config-string.json
                  fi          


