# Config for the setup workflow and common resources (jobs, commands) for main workflows
# `common-` prefix is added for common resources (to avoid conflicts with module resources)
# Adding in another comment to trigger a pull request

version: 2.1

setup: true

orbs:
  continuation: circleci/continuation@0.2.0

workflows:
  # The setup workflow
  setup:
    jobs:
      - continuation/continue:
          configuration_path: ".circleci/continue_config.yml"
          parameters: /home/circleci/test.json
          pre-steps:
            - checkout
            - run:
                name: Determine if we need to persist and export components
                command: |
                  echo $CIRCLE_PULL_REQUEST
                  if [[! -z "$CIRCLE_PULL_REQUEST"]];
                  then
                    echo '{ "EXEC_WF1": true }' >> /home/circleci/test.json
                  else
                    echo '{ "EXEC_WF2": true }' >> /home/circleci/test.json
                  fi          


